spring:
  application:
    name: Ecom_User_Service
  datasource:
    url: jdbc:mysql://localhost:3306/Ecom_User_Service
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8086
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
